name: web_annotation
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohttp==3.7.2
      - async-timeout==3.0.1
      - attrs==20.3.0
      - blis==0.4.1
      - boto3==1.16.15
      - botocore==1.19.16
      - brotlipy==0.7.0
      - cachetools==4.2.4
      - catalogue==1.0.2
      - certifi==2025.10.5
      - cffi==1.14.3
      - chardet==3.0.4
      - click==7.1.2
      - cryptography==3.2.1
      - cycler==0.10.0
      - cymem==2.0.4
      - decorator==4.4.2
      - dgl==0.4.3.post2
      - docutils==0.15.2
      - dominate==2.9.1
      - en-core-web-sm==2.3.1
      - filelock==3.16.1
      - fire==0.7.1
      - flask==1.1.2
      - flask-bootstrap==3.3.7.1
      - flask-wtf==0.14.3
      - future==0.18.2
      - gensim==3.8.3
      - gevent==20.12.0
      - google-api-core==1.22.2
      - google-auth==1.23.0
      - google-cloud-core==1.4.3
      - google-cloud-storage==1.32.0
      - google-crc32c==1.6.0.dev2
      - google-resumable-media==1.1.0
      - googleapis-common-protos==1.52.0
      - greenlet==0.4.17
      - gunicorn==23.0.0
      - idna==2.10
      - importlib-metadata==4.13.0
      - itsdangerous==1.1.0
      - jieba==0.39
      - jinja2==2.11.2
      - jmespath==0.10.0
      - joblib==0.17.0
      - jsonschema==3.0.2
      - kiwisolver==1.3.0
      - ltp==4.0.10
      - markupsafe==1.1.1
      - matplotlib==3.3.2
      - multidict==4.7.6
      - murmurhash==1.0.2
      - networkx==2.5
      - numpy==1.19.4
      - olefile==0.46
      - packaging==20.4
      - pandas==1.0.3
      - pillow==10.4.0
      - pip==25.0.1
      - plac==0.9.6
      - preshed==3.0.2
      - protobuf==3.14.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.20
      - pygtrie==2.3.3
      - pyopenssl==19.1.0
      - pyparsing==2.4.7
      - pyrsistent==0.17.3
      - pysocks==1.7.1
      - python-dateutil==2.8.1
      - pytz==2020.1
      - regex==2020.11.13
      - requests==2.25.0
      - rsa==4.6
      - s3transfer==0.3.3
      - sacremoses==0.0.43
      - scikit-learn==0.22.1
      - scikit-plot==0.3.7
      - scipy==1.5.2
      - sentencepiece==0.1.94
      - setuptools==58.0.0
      - six==1.15.0
      - smart-open==6.3.0
      - spacy==2.3.2
      - srsly==1.0.2
      - termcolor==1.1.0
      - thinc==7.4.1
      - thulac==0.2.1
      - tokenizers==0.9.2
      - toml==0.10.2
      - torch==1.6.0+cpu
      - torchtext==0.7.0
      - torchvision==0.7.0+cpu
      - tornado==6.0.4
      - tqdm==4.52.0
      - transformers==3.4.0
      - typing-extensions==3.7.4.3
      - urllib3==1.25.11
      - visitor==0.1.3
      - wasabi==0.8.0
      - werkzeug==1.0.1
      - wheel==0.45.1
      - wtforms==2.3.3
      - xlrd==1.2.0
      - yarl==1.5.1
      - zipp==3.4.0
      - zope-event==5.0
      - zope-interface==7.2
prefix: /root/miniconda3/envs/web_annotation
